if not E2Helper then return end

E2Helper.Descriptions["isTIV(e:)"] = "Returns 1 if entity is a supported Tornado Intercept Vehicle, 0 otherwise."
E2Helper.Descriptions["tivState(e:)"] = "Returns the deployment state of the TIV (idle, lowering, deploying_spikes, anchored, retracting, raising, lofted)."
E2Helper.Descriptions["tivIsDeployed(e:)"] = "Returns 1 if the TIV is fully deployed and anchored, 0 otherwise."
E2Helper.Descriptions["tivIsAnchored(e:)"] = "Returns 1 if the TIV is anchored, 0 otherwise."
E2Helper.Descriptions["tivIsTransitioning(e:)"] = "Returns 1 if the TIV is transitioning (deploying or retracting), 0 otherwise."
E2Helper.Descriptions["tivWindSpeed(e:)"] = "Returns the wind speed at the TIV in MPH."
E2Helper.Descriptions["tivWindDirection(e:)"] = "Returns the wind direction vector at the TIV."
E2Helper.Descriptions["tivStress(e:)"] = "Returns the anchor wind stress (0.0 to 1.0) on the TIV."
E2Helper.Descriptions["tivSpikeCount(e:)"] = "Returns the total number of installed spikes on the TIV."
E2Helper.Descriptions["tivSpikeState(e:)"] = "Returns the overall spike state (idle, deploying, deployed, retracting, none)."
E2Helper.Descriptions["tivAnchorIntegrity(e:)"] = "Returns 1 if the TIV anchor integrity is holding, 0 if compromised."
E2Helper.Descriptions["tivIsLofted(e:)"] = "Returns 1 if the TIV is lofted in a tornado, 0 otherwise."
E2Helper.Descriptions["tivController(e:)"] = "Returns the Wire controller entity linked to the TIV."
E2Helper.Descriptions["tivDeploy(e:)"] = "Starts deployment of the TIV (initiates lowering, spikes, anchoring)."
E2Helper.Descriptions["tivRetract(e:)"] = "Starts retraction of the TIV (unanchors, retracts spikes, raises vehicle)."
E2Helper.Descriptions["tivToggle(e:)"] = "Toggles deploy/retract of the TIV."
E2Helper.Descriptions["tivEmergencyStop(e:)"] = "Aborts the active deploy sequence and recovers the TIV to idle."
E2Helper.Descriptions["tivReset(e:)"] = "Resets the TIV systems, clears failure states, and restores fresh spikes."
E2Helper.Descriptions["tivPoints(e:)"] = "Returns the driver's current spendable upgrade points."
E2Helper.Descriptions["tivTotalPoints(e:)"] = "Returns the driver's lifetime total points earned."
E2Helper.Descriptions["tivIntercepts(e:)"] = "Returns the driver's total count of successful tornado intercepts."
E2Helper.Descriptions["tivCurrentIntercepts(e:)"] = "Returns the driver's current spendable upgrade points (legacy alias)."
E2Helper.Descriptions["tivTotalIntercepts(e:)"] = "Returns the driver's lifetime total intercepts (legacy alias)."
E2Helper.Descriptions["tivUpgradeCount(e:)"] = "Returns the number of unlocked upgrades for the driver."
E2Helper.Descriptions["tivHasUpgrade(e:s)"] = "Returns 1 if the driver has unlocked the specified upgrade ID, 0 otherwise."
E2Helper.Descriptions["tivArmorCount(e:)"] = "Returns the number of armor panels installed on the TIV."
E2Helper.Descriptions["tivArmorProtection(e:)"] = "Returns the kinetic impact debris protection percentage (0 to 100)."
E2Helper.Descriptions["tivLoftThreshold(e:)"] = "Returns the effective loft wind threshold in MPH (including upgrades)."
E2Helper.Descriptions["tivWindResistanceScale(e:)"] = "Returns the aerodynamic wind drag resistance scale (lower = more aerodynamic)."
E2Helper.Descriptions["tivTornadoDetected(e:)"] = "Returns 1 if an active tornado is within radar tracking range, 0 otherwise."
E2Helper.Descriptions["tivTornadoDistance(e:)"] = "Returns the distance to the nearest active tornado in hammer units."
E2Helper.Descriptions["tivTornadoBearing(e:)"] = "Returns the ABSOLUTE MAP bearing (0-360 deg, measured from world +X toward +Y) to the nearest active tornado. It does not change when the vehicle turns -- use tivTornadoRelativeBearing() for track-up displays."
E2Helper.Descriptions["tivTornadoRelativeBearing(e:)"] = "Returns the bearing of the nearest tornado in degrees (0-360) relative to the vehicle's nose: 0=ahead, 90=right, 180=astern, 270=left."
E2Helper.Descriptions["tivTornadoRelativeSector(e:)"] = "Returns the sector of the nearest tornado relative to the vehicle's nose: 0=ahead, 1=right, 2=astern, 3=left."
E2Helper.Descriptions["tivTornadoSpeed(e:)"] = "Returns the translation speed of the nearest active tornado in MPH."
E2Helper.Descriptions["tivTornadoETA(e:)"] = "Returns the estimated time to closest point of approach (ETA in seconds)."
E2Helper.Descriptions["tivTornadoImpactType(e:)"] = "Returns the tornado impact classification: 0=receding, 1=miss, 2=side sweep, 3=direct core hit."
